<?php include('partials/header.phtml'); ?>

        <div class="container">
            <div class="well">
<?php foreach($plugins as $pluginName => $pluginData): ?>
                <a href="#plugin-<?= $pluginName ?>" class="btn btn-margin-bottom <?= $pluginData['status']==\Model\PluginResultModel::PLUGIN_STATUS_FAILED ? 'btn-danger' : 'btn-primary' ?>" role="button"<?= !isset($pluginData['output']) || $pluginData['output']===false || !strlen($pluginData['output'])>0 ? ' disabled' : '' ?>>
                    <?php if($pluginData['success']): ?><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> <?php endif; ?>
                    <?= $pluginName ?>
<?php if(isset($layoutConfig['printPluginRuntime']) && $layoutConfig['printPluginRuntime']) { echo '&nbsp;('.$pluginData['time'].'s)'; }?>
                </a>
<?php endforeach; ?>
            </div>

<?php foreach($plugins as $pluginName => $pluginData): ?>
<?php $hasOutput = (isset($pluginData['output']) && $pluginData['output']!==false && strlen($pluginData['output'])>0) || $pluginData['runmode']==\Core\PluginRunner::RUN_PLUGIN_ASYNC; ?>
<?php if(!$hasOutput) { continue; } ?>
            <div id="plugin-<?= $pluginName ?>" class="well">
                <div class="row">
                    <div class="col-xs-9 col-sm-10 col-md-11">
                        <a name="plugin-<?= $pluginName ?>"></a>
                        <h2 class="text-primary nomargin-top">
                            <?php if($pluginData['success']): ?><span class="glyphicon glyphicon-exclamation-sign text-danger" aria-hidden="true"></span> <?php endif; ?><?= $pluginName ?>
                        </h2>
                    </div>
                    <div class="col-xs-3 col-sm-2 col-md-1 text-right">
                        <a href="#" role="button" class="btn btn-default">top</a>
                    </div>
                </div>
                <div>
<?php if($pluginData['runmode']==\Core\PluginRunner::RUN_PLUGIN_ASYNC): ?>
                    PLUGIN HAS TO RUN ASYNC<br>
                    TODO: Pass PluginResultModel to view!
<?php else: ?>
                    <?= $pluginData['output'] ?>
<?php endif; ?>
                </div>
            </div>
<?php endforeach; ?>
            
        </div>

<?php include('partials/footer.phtml'); ?>

