<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>GC Analyzer</title>

        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="Layout/css/style.css" rel="stylesheet">

        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <header class="bg-primary">
            <h1 class="nomargin-top text-center">GC Analyzer</h1>
        </header>

        <div class="container">
            <div class="well">
<?php foreach($pluginData as $pluginName => $data): ?>
                <a href="#plugin-<?= $pluginName ?>" class="btn btn-primary" role="button">
                    <?php if($data['success']): ?><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> <?php endif; ?>
                    <?= $pluginName ?>
                </a>
<?php endforeach; ?>
            </div>

<?php foreach($pluginData as $pluginName => $data): ?>
<?php if(!isset($data['output']) || $data['output']===false || !strlen($data['output'])>0) { continue; } ?>
            <div id="plugin-<?= $pluginName ?>" class="well">
                <a name="plugin-<?= $pluginName ?>"></a>
                <h2 class="text-primary nomargin-top">
                    <?php if($data['success']): ?><span class="glyphicon glyphicon-exclamation-sign text-danger" aria-hidden="true"></span> <?php endif; ?><?= $pluginName ?>
                </h2>
                <div>
                    <?= $data['output'] ?>
                </div>
            </div>
<?php endforeach; ?>
            
        </div>

        <footer class="bg-primary">
            <div class="text-center">by Blainnn &amp frigidor.
                See <a href="https://github.com/pascalbuehler/gc-analyzer" target="_blank">GitHub</a>
            </div>
        </footer>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </body>
</html>
